version: '3.9'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app           # монтируем локальну папку проекту в контейнер
      - ./db.sqlite3:/app/db.sqlite3  # монтируем файл SQLite, щоб база зберігалась локально
    ports:
      - "8000:8000"













        
