version: '3.9'

services:
  web:
    build: .
    command: gunicorn cicd_online_shop_lab4.wsgi:application --bind 0.0.0.0:8000

    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://cicdlab4:wMH5M9JKsTUZMFg72lyv6xd15DHQrKl6@dpg-d0qrh0buibrs73esja0g-a.frankfurt-postgres.render.com/cicdlab4
      - DJANGO_SETTINGS_MODULE=cicd_online_shop_lab4.settings

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: cicdlab4
      POSTGRES_PASSWORD: wMH5M9JKsTUZMFg72lyv6xd15DHQrKl6
      POSTGRES_DB: cicdlab4
    volumes:
      - .:/app
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
