name: CI - Build, Test and Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image for tests
        run: docker build -t myapp:test .

      - name: Run container, collect static files and execute tests
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -v ${{ github.workspace }}/db.sqlite3:/app/db.sqlite3 \
            myapp:test bash -c "python manage.py collectstatic --noinput && python manage.py test --keepdb"

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render deploy via deploy hook
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
